### ISSUE TITLE
Integer Representations

### ISSUE THREAD

**Issue by nnamon** [JRWR/Defcon-LoRaMesh#1]
Keeping the textual constraints, I propose that the format of the ’msgid’ and ’msglen’ fields be of length 4 and in hexadecimal. Parsers should only allow valid characters from the hexadecimal character set with no prefixes. This will avoid the issue of users attempting to set the length of messages larger than 65535 in the raw protocol since the greatest value representable is ffff.

**Comment by cyberbalsa** [comment]
I like it, APPROVED!
